<?xml version="1.0"?>
<robot
    name="gazebo_ros_four_wheel_steering_test_vehicle"
    xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/four_wheel_steering.urdf.xacro" />
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/inertia_tensors.urdf.xacro" />
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/primitives.urdf.xacro" />
  <xacro:include filename="wheel.urdf.xacro" />

  <xacro:property
      name="axle_width"
      value="1" />

  <xacro:property
      name="axle_wheel_offset_y"
      value="0.09" />

  <xacro:property
      name="wheel_base"
      value="1.42" />

  <link name="chassis">
    <xacro:box_inertial_with_origin
        mass="100.0"
        x="2"
        y="0.6"
        z="0.6">
      <origin xyz="-0.05 0 -0.1" />
    </xacro:box_inertial_with_origin>
    <xacro:box_primitive_with_origin
        x="2"
        y="0.6"
        z="0.6">
      <origin xyz="0 0 0.4" />
    </xacro:box_primitive_with_origin>
  </link>

  <xacro:property
      name="wheel_length"
      value="0.29" />
  <xacro:property
      name="wheel_radius"
      value="0.3495" />
  <!-- mass of tires including wheel rim -->
  <xacro:property
      name="mass_wheel"
      value="30.0" />

  <xacro:property
      name="steering_gear_triangle_length"
      value="0.1" />
  <xacro:property
      name="socket_x"
      value="${steering_gear_triangle_length * sin(60 / 180 * pi)}" />
  <xacro:property
      name="socket_y"
      value="${steering_gear_triangle_length * cos(60 / 180 * pi)}" />

  <xacro:property
      name="gear_x"
      value="${wheel_base / 2 - 0.25}" />

  <xacro:four_wheel_steering
      parent="chassis"
      front_origin_x="${wheel_base / 2}"
      rear_origin_x="${-wheel_base / 2}"
      axle_width="${axle_width}"
      gear_x="${gear_x}"
      socket_x="${gear_x + socket_x}"
      socket_y="${socket_y}"
      rod_x="${wheel_base / 2 - 0.125}"
      rod_y="${axle_width / 2 - 0.03}"
      z="0"
      z_sdf="0" />

  <xacro:wheel
      wheel_prefix="front_left"
      parent_link="front_left_axle">
    <origin
        xyz="0 ${axle_wheel_offset_y} 0"
        rpy="${pi/2} 0 0" />
  </xacro:wheel>

  <xacro:wheel
      wheel_prefix="front_right"
      parent_link="front_right_axle">
    <origin
        xyz="0 ${-axle_wheel_offset_y} 0"
        rpy="${pi/2} 0 0" />
  </xacro:wheel>

  <xacro:wheel
      wheel_prefix="rear_left"
      parent_link="rear_left_axle">
    <origin
        xyz="0 ${axle_wheel_offset_y} 0"
        rpy="${pi/2} 0 0" />
  </xacro:wheel>

  <xacro:wheel
      wheel_prefix="rear_right"
      parent_link="rear_right_axle">
    <origin
        xyz="0 ${-axle_wheel_offset_y} 0"
        rpy="${pi/2} 0 0" />
  </xacro:wheel>

  <gazebo>
    <plugin
        name="gazebo_ros_4ws"
        filename="libgazebo_ros_four_wheel_steering.so">
        <ros>
            <parameter name="front_right_motor.kp" type="double">400.0</parameter>
            <parameter name="front_right_motor.ki" type="double">10.0</parameter>
            <parameter name="front_right_motor.kd" type="double">1.0</parameter>

            <parameter name="front_left_motor.kp" type="double">400.0</parameter>
            <parameter name="front_left_motor.ki" type="double">10.0</parameter>
            <parameter name="front_left_motor.kd" type="double">1.0</parameter>

            <parameter name="rear_right_motor.kp" type="double">400.0</parameter>
            <parameter name="rear_right_motor.ki" type="double">10.0</parameter>
            <parameter name="rear_right_motor.kd" type="double">1.0</parameter>

            <parameter name="rear_left_motor.kp" type="double">400.0</parameter>
            <parameter name="rear_left_motor.ki" type="double">10.0</parameter>
            <parameter name="rear_left_motor.kd" type="double">1.0</parameter>

            <parameter name="front_steering.kp" type="double">4000.0</parameter>
            <parameter name="front_steering.ki" type="double">100.0</parameter>
            <parameter name="front_steering.kd" type="double">2.0</parameter>

            <parameter name="rear_steering.kp" type="double">4000.0</parameter>
            <parameter name="rear_steering.ki" type="double">100.0</parameter>
            <parameter name="rear_steering.kd" type="double">2.0</parameter>
        </ros>
      <steering_gear_transmission_ratio>1.6</steering_gear_transmission_ratio>
    </plugin>
  </gazebo>
</robot>