<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property
      name="gear_size"
      value="0.1" />

  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/wheel_steered.urdf.xacro" />
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/steering_rod.sdf.xacro" />
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/primitives.sdf.xacro" />
  <xacro:include filename="$(arg gazebo_ros_four_wheel_steering_prefix)/urdf/inertia_tensors.sdf.xacro" />

  <!--
  prefix: front, rear
  parent link: should be vehicle chassis
  gear_x: x position of steering gear, assumed y = 0 as in the center of the vehicle
  socket_x: offset from gear to rod socket x position
  socket_y: offset from gear to rod socket y position
  -->
  <xacro:macro
      name="axle"
      params="prefix parent x width gear_x socket_x socket_y rod_x rod_y z *origin">

    <xacro:wheel_steered
        prefix="${prefix}_left"
        parent_link="${parent}"
        left_right="1">
      <origin xyz="${x} ${width / 2} ${z}" />
    </xacro:wheel_steered>

    <xacro:wheel_steered
        prefix="${prefix}_right"
        parent_link="${parent}"
        left_right="-1">
      <origin xyz="${x} ${-width / 2} ${z}" />
    </xacro:wheel_steered>

    <!-- SDF-only steering system -->
    <gazebo>
      <link name="${prefix}_steering_gear">
        <pose>
          ${gear_x} 0 ${z} 0 0 0
        </pose>
        <xacro:sdf_box_inertia
            x="${gear_size}"
            y="${gear_size}"
            z="${gear_size}"
            mass="1" />
        <xacro:sdf_cylinder_primitive
            name="${prefix}"
            length="${gear_size}"
            radius="${gear_size}" />
      </link>

      <joint
          name="${prefix}_steering"
          type="revolute">
        <parent>chassis</parent>
        <child>${prefix}_steering_gear</child>
        <axis>
          <xyz>0 0 1</xyz>
          <limit>
            <lower>-0.515446875</lower>
            <upper>0.515446875</upper>
            <effort>1000</effort>
            <velocity>1.1914</velocity>
          </limit>
          <dynamics>
            <damping>1</damping>
            <friction>2</friction>
          </dynamics>
        </axis>
        <physics>
          <ode>
            <cfm_damping>1</cfm_damping>
          </ode>
        </physics>
      </joint>
      <xacro:steering_rod
          front_prefix="${prefix}"
          side_prefix="left"
          socket_x="${socket_x}"
          socket_y="${socket_y}"
          rod_x="${rod_x}"
          rod_y="${rod_y}"
          z="${z}" />
      <xacro:steering_rod
          front_prefix="${prefix}"
          side_prefix="right"
          socket_x="${socket_x}"
          socket_y="${-socket_y}"
          rod_x="${rod_x}"
          rod_y="${-rod_y}"
          z="${z}" />
    </gazebo>

  </xacro:macro>
</robot>
